version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: remit-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    environment:
      - AWS_ACCESS_KEY_ID=localkey
      - AWS_SECRET_ACCESS_KEY=localsecret
      - AWS_REGION=us-east-1

volumes:
  dynamodb-data:
    driver: local 