package com.remitservice.integration.upi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Response model for UPI payment request creation.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UpiPaymentResponse {
    
    /**
     * UPI payment ID generated by the UPI provider
     */
    @JsonProperty("paymentId")
    private String paymentId;
    
    /**
     * Merchant reference ID (our transactionId or paymentId)
     */
    @JsonProperty("reference")
    private String reference;
    
    /**
     * Status of the payment request creation
     */
    @JsonProperty("status")
    private String status;
    
    /**
     * UPI VPA (Virtual Payment Address) for payment
     */
    @JsonProperty("upiId")
    private String upiId;
    
    /**
     * Amount to be paid
     */
    @JsonProperty("amount")
    private Double amount;
    
    /**
     * Currency code
     */
    @JsonProperty("currency")
    private String currency;
    
    /**
     * Deep link for UPI app
     */
    @JsonProperty("deepLink")
    private String deepLink;
    
    /**
     * QR code for UPI payment (base64 encoded)
     */
    @JsonProperty("qrCode")
    private String qrCode;
    
    /**
     * Expiration timestamp for the payment request
     */
    @JsonProperty("expiresAt")
    private LocalDateTime expiresAt;
} 